### ISSUE TITLE
Unrecognized character found in trait file

### ISSUE THREAD

**Issue by shaodongyan** [AdmiralenOla/Scoary#105]
Command: /opt/anaconda3/envs/scoary/bin/scoary -g gene_presence_absence_roary.csv -t Hostgroup_membership.csv -p 1 -c BH --no_pairwise
Performing no pairwise comparisons. Ignoring all tree related options (user tree, population aware-correction, permutations).
Reading gene presence absence file
Ignoring relatedness among input sample and performing only population structure-naive analysis.
Reading traits file
CRITICAL:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/scoary/lib/python3.6/site-packages/scoary/methods.py", line 268, in main
    strains)
  File "/opt/anaconda3/envs/scoary/lib/python3.6/site-packages/scoary/methods.py", line 579, in Csv_to_dic
    "values (no commas): %s" % str(",".join(allowed_values)))
SystemExit: Unrecognized character found in trait file. Allowed values (no commas): 0,1,NA,.,-, ,
Unrecognized character found in trait file. Allowed values (no commas): 0,1,NA,.,-, ,

[Hostgroup_membership.csv](https://github.com/AdmiralenOla/Scoary/files/10202166/Hostgroup_membership.csv)

But My file is normal .could help me ? Thanks!

**Comment by ne1al** [comment]
@shaodongyan I had the same error too while they recommend CSV file, did you figure it out?

**Comment by ne1al** [comment]
@shaodongyan I tried something and it worked. Leave the first column totally empty. The second column should contain the sample names but without header, traits column can have header. I hope this works for you!
