### ISSUE TITLE
Maximum recursion depth

### ISSUE THREAD

**Issue by AdmiralenOla** [AdmiralenOla/Scoary#56]
As originally reported by @dutchscientist in #53 , Scoary currently throws a
```
RuntimeError: maximum recursion depth exceeded while calling a Python object
```
when attempting to perform pairwise comparisons on a too big dataset. The exact threshold is unknown to me. I have ran it with ~3500 isolates. This error was reported with ~5800.

Full message:
```
Storing results: ST45
Calculating max number of contrasting pairs for each nominally significant gene
100.00%Traceback (most recent call last):
File "/usr/local/bin/scoary", line 11, in 
load_entry_point('scoary==1.6.9', 'console_scripts', 'scoary')()
File "/usr/local/lib/python2.7/dist-packages/scoary-1.6.9-py2.7.egg/scoary/methods.py", line 244, in main
delimiter=args.delimiter)
File "/usr/local/lib/python2.7/dist-packages/scoary-1.6.9-py2.7.egg/scoary/methods.py", line 813, in StoreResults
num_threads, no_time, delimiter)
File "/usr/local/lib/python2.7/dist-packages/scoary-1.6.9-py2.7.egg/scoary/methods.py", line 920, in StoreTraitResult
Threadresults = list(Threadresults)
File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
raise value
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by snayfach** [comment]
Did you ever find a solution? I'm running into this issue using only 500 genomes.

**Comment by dutchscientist** [comment]
I never run it with pairwise comparisons; does it work with --no_pairwise? That should tell you whether it is a problem with your input files or with the pairwise comparisons.

**Comment by snayfach** [comment]
Yes it works with --no_pairwise. But that defeats the main purpose of Scoary, which is to control for the population structure, no?

**Comment by dutchscientist** [comment]
That depends on what you use it for. For my work the --no_pairwise is fine, but I am not hardcore population structure ;)

**Comment by MrTomRod** [comment]
Try adding this line to `methods.py`:

```python3
sys.setrecursionlimit(100000)
```

The number of recursions that is necessary for tree traversal is equal to the number of nodes in the tree, i.e. `n_nodes = 2 * n_leafs - 1`, so for 500 samples, 999 should be enough for the picking algorithm.
