### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'README_pypi.md'

### ISSUE THREAD

**Issue by tseemann** [AdmiralenOla/Scoary#60]
I am unable to upgrade my existing Scoary installation:

```
pip3 install --upgrade scoary
Collecting scoary
  Using cached scoary-1.6.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/linuxbrew/pip-build-4n646sv8/scoary/setup.py", line 14, in <module>
        long_description=readme(),
      File "/tmp/linuxbrew/pip-build-4n646sv8/scoary/setup.py", line 7, in readme
        with open('README_pypi.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README_pypi.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/linuxbrew/pip-build-4n646sv8/scoary/
```

**Comment by AdmiralenOla** [comment]
Thanks for reporting! Not exactly sure what's causing this and not able to replicate it myself. Could you try running:
```
pip3 install --upgrade git+https://github.com/AdmiralenOla/scoary.git@development
```
and see if that helps?

**Comment by tseemann** [comment]
That works. Still not sure what is wrong with pip. same error for pip2 and pip3. Ah well. It might fix itself.
