### ISSUE TITLE
Startcol error

### ISSUE THREAD

**Issue by GillNdhlovu** [AdmiralenOla/Scoary#97]
==== Scoary started ====
Command: /Users/nondumisondhlovu/opt/anaconda3/bin/scoary -g gene_presence_absence.csv -t case.csv -s 15
Reading gene presence absence file
CRITICAL:
Traceback (most recent call last):
  File "/Users/nondumisondhlovu/opt/anaconda3/lib/python3.8/site-packages/scoary/methods.py", line 359, in Csv_to_dic_Roary
    header[startcol]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nondumisondhlovu/opt/anaconda3/lib/python3.8/site-packages/scoary/methods.py", line 208, in main
    Csv_to_dic_Roary(genes,
  File "/Users/nondumisondhlovu/opt/anaconda3/lib/python3.8/site-packages/scoary/methods.py", line 361, in Csv_to_dic_Roary
    sys.exit("The startcol (-s) you have specified does not seem to "
SystemExit: The startcol (-s) you have specified does not seem to correspond to any column in your gene presence/absence file.
The startcol (-s) you have specified does not seem to correspond to any column in your gene presence/absence file.

**Comment by AdmiralenOla** [comment]
Hi @GillNdhlovu . Sorry that I am only replying to this now.

My guess is you are not using a gene presence/absence file from Roary? You then have to manually set the number of the column (startcol) where the actual gene presence/absence data starts. In Roary this column number is 15, but it that number will be something else if you are not using Roary. If you are not able to tell yourself, perhaps you can post the first few rows of your file here so that I might be able to help you.
